# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
import os.path

ENDPOINT_EXECUTION_ROLE = ...
MODEL_TRAINING_ROLE = ...

REGION_NAME = ...


DATA_BUCKET_NAME = ...
MODEL_BUCKET_NAME = ...
QUERY_BUCKET_NAME = ...
SCRIPT_BUCKET_NAME = ...
TRAINING_DIR_NAME = "training_data"
TESTING_DIR_NAME = "testing_data"
MODEL_OUTPUT_DIR_NAME = "model_output"

MNIST_PREFIX = "MNIST"
_MNIST_TRAINING_FEATURES_NAME = "mnist_training_features.npy"
_MNIST_TRAINING_LABELS_NAME = "mnist_training_labels.npy"
_MNIST_TESTING_FEATURES_NAME = "mnist_testing_features.npy"
_MNIST_TESTING_LABELS_NAME = "mnist_testing_labels.npy"

MNIST_DIR = ...
MNIST_TRAINING_FEATURES_PATH = os.path.join(
    MNIST_DIR, TRAINING_DIR_NAME, _MNIST_TRAINING_FEATURES_NAME
)
MNIST_TRAINING_LABELS_PATH = os.path.join(
    MNIST_DIR, TRAINING_DIR_NAME, _MNIST_TRAINING_LABELS_NAME
)
MNIST_TESTING_FEATURES_PATH = os.path.join(
    MNIST_DIR, TESTING_DIR_NAME, _MNIST_TESTING_FEATURES_NAME
)
MNIST_TESTING_LABELS_PATH = os.path.join(
    MNIST_DIR, TESTING_DIR_NAME, _MNIST_TESTING_LABELS_NAME
)
MNIST_MODEL_OUTPUT_DIR = os.path.join(MNIST_DIR, MODEL_OUTPUT_DIR_NAME)

ECR_REGISTRY = ...
ECR_REPO_TRAINING = ...
ECR_REPO_INFERENCE = ...
