# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

FROM python:3.12

RUN apt-get -y update && apt-get install -y --no-install-recommends \
         nginx \
         ca-certificates \
         cmake \
    && rm -rf /var/lib/apt/lists/*

RUN pip install Flask==3.1.3 gevent==25.9.1 gunicorn==25.1.0 sagemaker==2.243.2 sagemaker_training==5.1.1 concrete-ml==1.9.0 concrete-python==2.10.0 torch==2.3.1
RUN rm -rf /root/.cache

# Set environment variables
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"


COPY container_files/ /opt/program
RUN chmod +x /opt/program/serve
WORKDIR /opt/program

